version: '3.3'
services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: apiki-challenge-wordpress
      MYSQL_USER: apiki-challenge-wordpress-geral
      MYSQL_PASSWORD: 123456
    volumes:
      - './db:/var/lib/mysql'
    ports:
      - '3324:3306'
  phpmyadmin:
    depends_on:
      - db
    image: 'phpmyadmin:5.2.0-apache'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '8099:80'
  web:
    depends_on:
      - db
    image: 'wordpress:5.9-php8.0-apache'
    volumes:
      - './src:/var/www/html'
      - './src/wp-content:/var/www/html/wp-content'
    ports:
      - '8000:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: apiki-challenge-wordpress-geral
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: apiki-challenge-wordpress
