services:
  db:
    image: mariadb:10.6.4-focal
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=apiki
      - MYSQL_DATABASE=wp_apiki
      - MYSQL_USER=vitorcampos
      - MYSQL_PASSWORD=apiki
    ports:
      - 3306:3306
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=vitorcampos
      - WORDPRESS_DB_PASSWORD=apiki
      - WORDPRESS_DB_NAME=wp_apiki
    volumes:
      - ./src:/var/www/html/wp-content/plugins
volumes:
  db_data: